# Form implementation generated from reading ui file 'engine.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from . import widgets_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 162)
        Dialog.setMinimumSize(QtCore.QSize(350, 162))
        Dialog.setMaximumSize(QtCore.QSize(350, 162))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/engine.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(25,25,25);\n"
"background-color: rgb(255, 255, 255);")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(0, 31))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 31))
        self.label_5.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.motor_isim = QtWidgets.QLineEdit(parent=Dialog)
        self.motor_isim.setMinimumSize(QtCore.QSize(157, 21))
        self.motor_isim.setMaximumSize(QtCore.QSize(157, 21))
        self.motor_isim.setObjectName("motor_isim")
        self.horizontalLayout_3.addWidget(self.motor_isim)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.frame_2 = QtWidgets.QFrame(parent=Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sec = QtWidgets.QPushButton(parent=self.frame_2)
        self.sec.setMinimumSize(QtCore.QSize(50, 21))
        self.sec.setMaximumSize(QtCore.QSize(50, 21))
        self.sec.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sec.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.sec.setStyleSheet("QPushButton{\n"
"border-radius:5px;\n"
"border:1px solid rgb(0,0,0);\n"
"font: 700 11px \"Segoe UI\";\n"
"color:rgb(25,25,25);\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(25,25,25);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(80,80,80);\n"
"}")
        self.sec.setDefault(False)
        self.sec.setObjectName("sec")
        self.horizontalLayout_6.addWidget(self.sec)
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(92, 0))
        self.label_2.setMaximumSize(QtCore.QSize(92, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.frame_3 = QtWidgets.QFrame(parent=Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.kaydet = QtWidgets.QPushButton(parent=self.frame_3)
        self.kaydet.setMinimumSize(QtCore.QSize(141, 21))
        self.kaydet.setMaximumSize(QtCore.QSize(141, 21))
        self.kaydet.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.kaydet.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.kaydet.setStyleSheet("QPushButton{\n"
"border-radius:5px;\n"
"font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);\n"
"background-color: rgb(25,25,25);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color:rgb(239, 239, 239);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"}")
        self.kaydet.setObjectName("kaydet")
        self.horizontalLayout_8.addWidget(self.kaydet)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(0, 15))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_4.setStyleSheet("color:rgba(20,20,20,0.5)")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Motor"))
        self.label_5.setText(_translate("Dialog", "Motor"))
        self.label.setText(_translate("Dialog", "Motor ismi"))
        self.sec.setText(_translate("Dialog", "Seç"))
        self.label_2.setText(_translate("Dialog", "Dosya"))
        self.label_3.setText(_translate("Dialog", "-"))
        self.kaydet.setText(_translate("Dialog", "KAYDET"))
        self.label_4.setText(_translate("Dialog", ".xlsx ve .xls uzantılı dosyalar desteklenmektedir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
