# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from . import main_rc

class Ui_VehicleDynamicsApp(object):
    def setupUi(self, VehicleDynamicsApp):
        VehicleDynamicsApp.setObjectName("VehicleDynamicsApp")
        VehicleDynamicsApp.setEnabled(True)
        VehicleDynamicsApp.resize(890, 623)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VehicleDynamicsApp.sizePolicy().hasHeightForWidth())
        VehicleDynamicsApp.setSizePolicy(sizePolicy)
        VehicleDynamicsApp.setMinimumSize(QtCore.QSize(890, 623))
        VehicleDynamicsApp.setMaximumSize(QtCore.QSize(890, 623))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(9)
        font.setItalic(False)
        font.setKerning(True)
        VehicleDynamicsApp.setFont(font)
        VehicleDynamicsApp.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        VehicleDynamicsApp.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icons/icon.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        VehicleDynamicsApp.setWindowIcon(icon)
        VehicleDynamicsApp.setToolTipDuration(-1)
        VehicleDynamicsApp.setStyleSheet("font: 350 9pt \"Bahnschrift SemiLight\";\n"
"background-color: rgb(28,28,28);\n"
"color:rgb(255,255,255);")
        VehicleDynamicsApp.setIconSize(QtCore.QSize(40, 40))
        VehicleDynamicsApp.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=VehicleDynamicsApp)
        self.centralwidget.setMinimumSize(QtCore.QSize(890, 546))
        self.centralwidget.setMaximumSize(QtCore.QSize(890, 609))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(890, 16777215))
        self.frame.setStyleSheet("background-color: rgb(5,5,5);")
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(4, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_side = QtWidgets.QFrame(parent=self.frame)
        self.left_side.setMinimumSize(QtCore.QSize(410, 542))
        self.left_side.setMaximumSize(QtCore.QSize(410, 542))
        self.left_side.setStyleSheet("font: 900 8pt \"Segoe UI\";\n"
"background-color: rgb(25,25,25);")
        self.left_side.setObjectName("left_side")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.left_side)
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_holder = QtWidgets.QFrame(parent=self.left_side)
        self.left_side_holder.setObjectName("left_side_holder")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.left_side_holder)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(10)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.pancar_image = QtWidgets.QLabel(parent=self.left_side_holder)
        self.pancar_image.setMinimumSize(QtCore.QSize(411, 301))
        self.pancar_image.setMaximumSize(QtCore.QSize(411, 301))
        self.pancar_image.setAutoFillBackground(False)
        self.pancar_image.setStyleSheet("border:10px solid rgba(250,250,250,.9);")
        self.pancar_image.setText("")
        self.pancar_image.setPixmap(QtGui.QPixmap(":/img/icons/dark-car-from-side-vector-9761198.jpg"))
        self.pancar_image.setScaledContents(True)
        self.pancar_image.setWordWrap(False)
        self.pancar_image.setOpenExternalLinks(False)
        self.pancar_image.setObjectName("pancar_image")
        self.pancar_image.setStyleSheet("margin:7px;\n""padding-right:1px;\n")
        self.verticalLayout_34.addWidget(self.pancar_image)
        self.info_input_area = QtWidgets.QWidget(parent=self.left_side_holder)
        self.info_input_area.setMinimumSize(QtCore.QSize(371, 161))
        self.info_input_area.setMaximumSize(QtCore.QSize(123213, 213123))
        self.info_input_area.setStyleSheet("")
        self.info_input_area.setObjectName("info_input_area")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.info_input_area)
        self.verticalLayout_35.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_35.setSpacing(20)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.left_seperator = QtWidgets.QLabel(parent=self.info_input_area)
        self.left_seperator.setMinimumSize(QtCore.QSize(0, 1))
        self.left_seperator.setMaximumSize(QtCore.QSize(16777215, 1))
        self.left_seperator.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.left_seperator.setText("")
        self.left_seperator.setObjectName("left_seperator")
        self.verticalLayout_35.addWidget(self.left_seperator)
        self.vehicle_info = QtWidgets.QGroupBox(parent=self.info_input_area)
        self.vehicle_info.setMinimumSize(QtCore.QSize(0, 110))
        self.vehicle_info.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.vehicle_info.setFont(font)
        self.vehicle_info.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.vehicle_info.setObjectName("vehicle_info")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.vehicle_info)
        self.verticalLayout_36.setSpacing(6)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.vehicle_info_holder = QtWidgets.QHBoxLayout()
        self.vehicle_info_holder.setObjectName("vehicle_info_holder")
        self.vehicle_info_label_area = QtWidgets.QWidget(parent=self.vehicle_info)
        self.vehicle_info_label_area.setStyleSheet("font: 12px \"Small Fonts\";")
        self.vehicle_info_label_area.setObjectName("vehicle_info_label_area")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.vehicle_info_label_area)
        self.verticalLayout_37.setSpacing(10)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.car_model_label = QtWidgets.QLabel(parent=self.vehicle_info_label_area)
        self.car_model_label.setObjectName("car_model_label")
        self.verticalLayout_37.addWidget(self.car_model_label)
        self.engine_model_label = QtWidgets.QLabel(parent=self.vehicle_info_label_area)
        self.engine_model_label.setObjectName("engine_model_label")
        self.verticalLayout_37.addWidget(self.engine_model_label)
        self.vehicle_info_holder.addWidget(self.vehicle_info_label_area)
        self.vehicle_info_input_area = QtWidgets.QVBoxLayout()
        self.vehicle_info_input_area.setSpacing(10)
        self.vehicle_info_input_area.setObjectName("vehicle_info_input_area")
        self.car_model = QtWidgets.QLineEdit(parent=self.vehicle_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_model.sizePolicy().hasHeightForWidth())
        self.car_model.setSizePolicy(sizePolicy)
        self.car_model.setMinimumSize(QtCore.QSize(200, 20))
        self.car_model.setMaximumSize(QtCore.QSize(200, 20))
        self.car_model.setStyleSheet("color:rgb(0,0,0);\n"
"background-color: rgb(168, 168, 168);")
        self.car_model.setObjectName("car_model")
        self.vehicle_info_input_area.addWidget(self.car_model)
        self.engine_model = QtWidgets.QLineEdit(parent=self.vehicle_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.engine_model.sizePolicy().hasHeightForWidth())
        self.engine_model.setSizePolicy(sizePolicy)
        self.engine_model.setMinimumSize(QtCore.QSize(200, 20))
        self.engine_model.setMaximumSize(QtCore.QSize(200, 20))
        self.engine_model.setStyleSheet("color:rgb(0,0,0);\n"
"background-color: rgb(168, 168, 168);")
        self.engine_model.setObjectName("engine_model")
        self.vehicle_info_input_area.addWidget(self.engine_model)
        self.vehicle_info_holder.addLayout(self.vehicle_info_input_area)
        self.verticalLayout_36.addLayout(self.vehicle_info_holder)
        self.verticalLayout_35.addWidget(self.vehicle_info)
        self.user_info = QtWidgets.QGroupBox(parent=self.info_input_area)
        self.user_info.setMinimumSize(QtCore.QSize(0, 70))
        self.user_info.setMaximumSize(QtCore.QSize(16777215, 70))
        self.user_info.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.user_info.setObjectName("user_info")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.user_info)
        self.verticalLayout_39.setContentsMargins(-1, 9, -1, 9)
        self.verticalLayout_39.setSpacing(6)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.user_info_holder = QtWidgets.QHBoxLayout()
        self.user_info_holder.setObjectName("user_info_holder")
        self.user_info_label_area = QtWidgets.QLabel(parent=self.user_info)
        self.user_info_label_area.setStyleSheet("font: 9pt \"Small Fonts\";")
        self.user_info_label_area.setObjectName("user_info_label_area")
        self.user_info_holder.addWidget(self.user_info_label_area)
        self.user_name = QtWidgets.QLineEdit(parent=self.user_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_name.sizePolicy().hasHeightForWidth())
        self.user_name.setSizePolicy(sizePolicy)
        self.user_name.setMinimumSize(QtCore.QSize(200, 20))
        self.user_name.setMaximumSize(QtCore.QSize(200, 20))
        self.user_name.setStyleSheet("color:rgb(0,0,0);\n"
"background-color: rgb(168, 168, 168);")
        self.user_name.setObjectName("user_name")
        self.user_info_holder.addWidget(self.user_name)
        self.verticalLayout_39.addLayout(self.user_info_holder)
        self.verticalLayout_35.addWidget(self.user_info)
        self.verticalLayout_34.addWidget(self.info_input_area)
        self.horizontalLayout.addWidget(self.left_side_holder)
        self.horizontalLayout_2.addWidget(self.left_side)
        self.right_side = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_side.sizePolicy().hasHeightForWidth())
        self.right_side.setSizePolicy(sizePolicy)
        self.right_side.setMinimumSize(QtCore.QSize(460, 542))
        self.right_side.setMaximumSize(QtCore.QSize(460, 542))
        self.right_side.setStyleSheet("")
        self.right_side.setObjectName("right_side")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.right_side)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.list_area = QtWidgets.QFrame(parent=self.right_side)
        self.list_area.setMinimumSize(QtCore.QSize(456, 1))
        self.list_area.setMaximumSize(QtCore.QSize(456, 123123))
        self.list_area.setStyleSheet("background-color: rgb(25,25,25);\n"
"border-radius:3px;")
        self.list_area.setObjectName("list_area")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.list_area)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.upper_lists_area = QtWidgets.QHBoxLayout()
        self.upper_lists_area.setObjectName("upper_lists_area")
        self.ets_engine_torque_speed = QtWidgets.QVBoxLayout()
        self.ets_engine_torque_speed.setObjectName("ets_engine_torque_speed")
        self.engine_torque_speed_list = QtWidgets.QListWidget(parent=self.list_area)
        self.engine_torque_speed_list.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"font: 10pt \"Segoe UI\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(102, 0, 0);\n"
"")
        self.engine_torque_speed_list.setObjectName("engine_torque_speed_list")
        item = QtWidgets.QListWidgetItem()
        self.engine_torque_speed_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.engine_torque_speed_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.engine_torque_speed_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.engine_torque_speed_list.addItem(item)
        self.ets_engine_torque_speed.addWidget(self.engine_torque_speed_list)
        self.ets_list_bottom = QtWidgets.QHBoxLayout()
        self.ets_list_bottom.setObjectName("ets_list_bottom")
        self.ets_list_label = QtWidgets.QLabel(parent=self.list_area)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.ets_list_label.setFont(font)
        self.ets_list_label.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.ets_list_label.setObjectName("ets_list_label")
        self.ets_list_bottom.addWidget(self.ets_list_label)
        self.ets_list_delete_button = QtWidgets.QPushButton(parent=self.list_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.ets_list_delete_button.sizePolicy().hasHeightForWidth())
        self.ets_list_delete_button.setSizePolicy(sizePolicy)
        self.ets_list_delete_button.setMinimumSize(QtCore.QSize(18, 18))
        self.ets_list_delete_button.setMaximumSize(QtCore.QSize(18, 18))
        self.ets_list_delete_button.setSizeIncrement(QtCore.QSize(0, 10))
        self.ets_list_delete_button.setBaseSize(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.ets_list_delete_button.setFont(font)
        self.ets_list_delete_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ets_list_delete_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ets_list_delete_button.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"padding-bottom:4px;\n"
"padding-left:1px;\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.ets_list_delete_button.setObjectName("ets_list_delete_button")
        self.ets_list_bottom.addWidget(self.ets_list_delete_button)
        self.ets_engine_torque_speed.addLayout(self.ets_list_bottom)
        self.upper_lists_area.addLayout(self.ets_engine_torque_speed)
        self.upper_list_seperator = QtWidgets.QLabel(parent=self.list_area)
        self.upper_list_seperator.setMinimumSize(QtCore.QSize(1, 100))
        self.upper_list_seperator.setMaximumSize(QtCore.QSize(1, 100))
        self.upper_list_seperator.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.upper_list_seperator.setText("")
        self.upper_list_seperator.setObjectName("upper_list_seperator")
        self.upper_lists_area.addWidget(self.upper_list_seperator)
        self.gearbox = QtWidgets.QVBoxLayout()
        self.gearbox.setObjectName("gearbox")
        self.gearbox_list = QtWidgets.QListWidget(parent=self.list_area)
        self.gearbox_list.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"font: 10pt \"Segoe UI\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(102, 0, 0);\n"
"")
        self.gearbox_list.setObjectName("gearbox_list")
        item = QtWidgets.QListWidgetItem()
        self.gearbox_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gearbox_list.addItem(item)
        self.gearbox.addWidget(self.gearbox_list)
        self.gearbox_list_bottom = QtWidgets.QHBoxLayout()
        self.gearbox_list_bottom.setObjectName("gearbox_list_bottom")
        self.gearbox_list_label = QtWidgets.QLabel(parent=self.list_area)
        self.gearbox_list_label.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.gearbox_list_label.setObjectName("gearbox_list_label")
        self.gearbox_list_bottom.addWidget(self.gearbox_list_label)
        self.gearbox_list_delete_button = QtWidgets.QPushButton(parent=self.list_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.gearbox_list_delete_button.sizePolicy().hasHeightForWidth())
        self.gearbox_list_delete_button.setSizePolicy(sizePolicy)
        self.gearbox_list_delete_button.setMinimumSize(QtCore.QSize(18, 18))
        self.gearbox_list_delete_button.setMaximumSize(QtCore.QSize(18, 18))
        self.gearbox_list_delete_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.gearbox_list_delete_button.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"padding-bottom:4px;\n"
"padding-left:1px;\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.gearbox_list_delete_button.setObjectName("gearbox_list_delete_button")
        self.gearbox_list_bottom.addWidget(self.gearbox_list_delete_button)
        self.gearbox.addLayout(self.gearbox_list_bottom)
        self.upper_lists_area.addLayout(self.gearbox)
        self.verticalLayout_8.addLayout(self.upper_lists_area)
        self.list_seperator = QtWidgets.QLabel(parent=self.list_area)
        self.list_seperator.setMinimumSize(QtCore.QSize(0, 1))
        self.list_seperator.setMaximumSize(QtCore.QSize(16777215, 1))
        self.list_seperator.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.list_seperator.setText("")
        self.list_seperator.setObjectName("list_seperator")
        self.verticalLayout_8.addWidget(self.list_seperator)
        self.lower_lists_area = QtWidgets.QHBoxLayout()
        self.lower_lists_area.setObjectName("lower_lists_area")
        self.vehicle = QtWidgets.QVBoxLayout()
        self.vehicle.setObjectName("vehicle")
        self.vehicle_list = QtWidgets.QListWidget(parent=self.list_area)
        self.vehicle_list.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"font: 10pt \"Segoe UI\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(102, 0, 0);\n"
"")
        self.vehicle_list.setObjectName("vehicle_list")
        item = QtWidgets.QListWidgetItem()
        self.vehicle_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vehicle_list.addItem(item)
        self.vehicle.addWidget(self.vehicle_list)
        self.vehicle_list_bottom = QtWidgets.QHBoxLayout()
        self.vehicle_list_bottom.setObjectName("vehicle_list_bottom")
        self.vehicle_list_label = QtWidgets.QLabel(parent=self.list_area)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.vehicle_list_label.setFont(font)
        self.vehicle_list_label.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.vehicle_list_label.setObjectName("vehicle_list_label")
        self.vehicle_list_bottom.addWidget(self.vehicle_list_label)
        self.vehicle_list_delete_button = QtWidgets.QPushButton(parent=self.list_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.vehicle_list_delete_button.sizePolicy().hasHeightForWidth())
        self.vehicle_list_delete_button.setSizePolicy(sizePolicy)
        self.vehicle_list_delete_button.setMinimumSize(QtCore.QSize(18, 18))
        self.vehicle_list_delete_button.setMaximumSize(QtCore.QSize(18, 18))
        self.vehicle_list_delete_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.vehicle_list_delete_button.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"padding-bottom:4px;\n"
"padding-left:1px;\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.vehicle_list_delete_button.setObjectName("vehicle_list_delete_button")
        self.vehicle_list_bottom.addWidget(self.vehicle_list_delete_button)
        self.vehicle.addLayout(self.vehicle_list_bottom)
        self.lower_lists_area.addLayout(self.vehicle)
        self.lower_list_seperator = QtWidgets.QLabel(parent=self.list_area)
        self.lower_list_seperator.setMinimumSize(QtCore.QSize(1, 100))
        self.lower_list_seperator.setMaximumSize(QtCore.QSize(1, 100))
        self.lower_list_seperator.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.lower_list_seperator.setText("")
        self.lower_list_seperator.setObjectName("lower_list_seperator")
        self.lower_lists_area.addWidget(self.lower_list_seperator)
        self.environment = QtWidgets.QVBoxLayout()
        self.environment.setObjectName("environment")
        self.environment_list = QtWidgets.QListWidget(parent=self.list_area)
        self.environment_list.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"font: 10pt \"Segoe UI\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(102, 0, 0);\n"
"")
        self.environment_list.setObjectName("environment_list")
        item = QtWidgets.QListWidgetItem()
        self.environment_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.environment_list.addItem(item)
        self.environment.addWidget(self.environment_list)
        self.envrionment_list_bottom = QtWidgets.QHBoxLayout()
        self.envrionment_list_bottom.setObjectName("envrionment_list_bottom")
        self.env_list_label = QtWidgets.QLabel(parent=self.list_area)
        self.env_list_label.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.env_list_label.setObjectName("env_list_label")
        self.envrionment_list_bottom.addWidget(self.env_list_label)
        self.env_list_delete_button = QtWidgets.QPushButton(parent=self.list_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.env_list_delete_button.sizePolicy().hasHeightForWidth())
        self.env_list_delete_button.setSizePolicy(sizePolicy)
        self.env_list_delete_button.setMinimumSize(QtCore.QSize(18, 18))
        self.env_list_delete_button.setMaximumSize(QtCore.QSize(18, 18))
        self.env_list_delete_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.env_list_delete_button.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"padding-bottom:4px;\n"
"padding-left:1px;\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.env_list_delete_button.setObjectName("env_list_delete_button")
        self.envrionment_list_bottom.addWidget(self.env_list_delete_button)
        self.environment.addLayout(self.envrionment_list_bottom)
        self.lower_lists_area.addLayout(self.environment)
        self.verticalLayout_8.addLayout(self.lower_lists_area)
        self.verticalLayout_10.addWidget(self.list_area)
        self.graph_area = QtWidgets.QGroupBox(parent=self.right_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_area.sizePolicy().hasHeightForWidth())
        self.graph_area.setSizePolicy(sizePolicy)
        self.graph_area.setMinimumSize(QtCore.QSize(456, 150))
        self.graph_area.setMaximumSize(QtCore.QSize(456, 150))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        self.graph_area.setFont(font)
        self.graph_area.setToolTipDuration(0)
        self.graph_area.setStyleSheet("selection-color: rgb(17, 17, 17);\n"
"font: 700 italic 9pt \"Segoe UI\";\n"
"color: #aa0000;\n"
"border-color: rgb(25, 25, 25);")
        self.graph_area.setObjectName("graph_area")
        self.gridLayout = QtWidgets.QGridLayout(self.graph_area)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.button_holder_2 = QtWidgets.QWidget(parent=self.graph_area)
        self.button_holder_2.setMinimumSize(QtCore.QSize(451, 126))
        self.button_holder_2.setMaximumSize(QtCore.QSize(451, 126))
        self.button_holder_2.setToolTipDuration(0)
        self.button_holder_2.setAutoFillBackground(False)
        self.button_holder_2.setStyleSheet("background-color: rgb(20,20,20);\n"
"border-color: rgb(25, 25, 25);\n"
"font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.button_holder_2.setObjectName("button_holder_2")
        self.button_holder = QtWidgets.QHBoxLayout(self.button_holder_2)
        self.button_holder.setContentsMargins(0, 0, 0, 10)
        self.button_holder.setSpacing(0)
        self.button_holder.setObjectName("button_holder")
        self.left_graphs = QtWidgets.QVBoxLayout()
        self.left_graphs.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.left_graphs.setContentsMargins(5, 0, -1, 0)
        self.left_graphs.setSpacing(0)
        self.left_graphs.setObjectName("left_graphs")
        self.enginev_vehiclev = QtWidgets.QPushButton(parent=self.button_holder_2)
        self.enginev_vehiclev.setMinimumSize(QtCore.QSize(180, 28))
        self.enginev_vehiclev.setMaximumSize(QtCore.QSize(180, 20))
        self.enginev_vehiclev.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.enginev_vehiclev.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.enginev_vehiclev.setIconSize(QtCore.QSize(16, 20))
        self.enginev_vehiclev.setObjectName("enginev_vehiclev")
        self.left_graphs.addWidget(self.enginev_vehiclev)
        self.torque_enginev = QtWidgets.QPushButton(parent=self.button_holder_2)
        self.torque_enginev.setMinimumSize(QtCore.QSize(180, 28))
        self.torque_enginev.setMaximumSize(QtCore.QSize(180, 20))
        self.torque_enginev.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.torque_enginev.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.torque_enginev.setObjectName("torque_enginev")
        self.left_graphs.addWidget(self.torque_enginev)
        self.torque_enginev_power = QtWidgets.QPushButton(parent=self.button_holder_2)
        self.torque_enginev_power.setEnabled(True)
        self.torque_enginev_power.setMinimumSize(QtCore.QSize(180, 28))
        self.torque_enginev_power.setMaximumSize(QtCore.QSize(180, 20))
        self.torque_enginev_power.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.torque_enginev_power.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.torque_enginev_power.setObjectName("torque_enginev_power")
        self.left_graphs.addWidget(self.torque_enginev_power)
        self.button_holder.addLayout(self.left_graphs)
        self.right_graphs_2 = QtWidgets.QFrame(parent=self.button_holder_2)
        self.right_graphs_2.setMinimumSize(QtCore.QSize(260, 0))
        self.right_graphs_2.setMaximumSize(QtCore.QSize(260, 16777215))
        self.right_graphs_2.setObjectName("right_graphs_2")
        self.right_graphs = QtWidgets.QVBoxLayout(self.right_graphs_2)
        self.right_graphs.setContentsMargins(5, -1, 9, -1)
        self.right_graphs.setObjectName("right_graphs")
        self.tractiveF_vehiclev = QtWidgets.QPushButton(parent=self.right_graphs_2)
        self.tractiveF_vehiclev.setMinimumSize(QtCore.QSize(250, 40))
        self.tractiveF_vehiclev.setMaximumSize(QtCore.QSize(250, 28))
        self.tractiveF_vehiclev.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.tractiveF_vehiclev.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.tractiveF_vehiclev.setObjectName("tractiveF_vehiclev")
        self.right_graphs.addWidget(self.tractiveF_vehiclev)
        self.tractiveFnet_vehiclev = QtWidgets.QPushButton(parent=self.right_graphs_2)
        self.tractiveFnet_vehiclev.setMinimumSize(QtCore.QSize(250, 40))
        self.tractiveFnet_vehiclev.setMaximumSize(QtCore.QSize(250, 28))
        self.tractiveFnet_vehiclev.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.tractiveFnet_vehiclev.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.tractiveFnet_vehiclev.setObjectName("tractiveFnet_vehiclev")
        self.right_graphs.addWidget(self.tractiveFnet_vehiclev)
        self.button_holder.addWidget(self.right_graphs_2)
        self.gridLayout.addWidget(self.button_holder_2, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.graph_area)
        self.horizontalLayout_2.addWidget(self.right_side)
        self.verticalLayout_2.addWidget(self.frame)
        VehicleDynamicsApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VehicleDynamicsApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 18))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(parent=self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menuHakk_nda = QtWidgets.QMenu(parent=self.menubar)
        self.menuHakk_nda.setObjectName("menuHakk_nda")
        VehicleDynamicsApp.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(parent=VehicleDynamicsApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(9)
        font.setItalic(False)
        font.setKerning(True)
        self.toolBar.setFont(font)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolBar.setAcceptDrops(True)
        self.toolBar.setToolTip("")
        self.toolBar.setStatusTip("")
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setObjectName("toolBar")
        VehicleDynamicsApp.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionKapat = QtGui.QAction(parent=VehicleDynamicsApp)
        font = QtGui.QFont()
        self.actionKapat.setFont(font)
        self.actionKapat.setObjectName("actionKapat")
        self.actionProgram_Kaynaklar = QtGui.QAction(parent=VehicleDynamicsApp)
        font = QtGui.QFont()
        self.actionProgram_Kaynaklar.setFont(font)
        self.actionProgram_Kaynaklar.setObjectName("actionProgram_Kaynaklar")
        self.vehicle_entry = QtGui.QAction(parent=VehicleDynamicsApp)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icons/vehicle.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vehicle_entry.setIcon(icon1)
        self.vehicle_entry.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.vehicle_entry.setObjectName("vehicle_entry")
        self.gearbox_entry = QtGui.QAction(parent=VehicleDynamicsApp)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icons/gearbox2.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.gearbox_entry.setIcon(icon2)
        self.gearbox_entry.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.gearbox_entry.setObjectName("gearbox_entry")
        self.environment_entry = QtGui.QAction(parent=VehicleDynamicsApp)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icons/road.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.environment_entry.setIcon(icon3)
        self.environment_entry.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.environment_entry.setObjectName("environment_entry")
        self.engine_entry = QtGui.QAction(parent=VehicleDynamicsApp)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/icons/engine.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.engine_entry.setIcon(icon4)
        self.engine_entry.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.engine_entry.setObjectName("engine_entry")
        self.actionDosyaya_Aktar = QtGui.QAction(parent=VehicleDynamicsApp)
        self.actionDosyaya_Aktar.setObjectName("actionDosyaya_Aktar")
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionDosyaya_Aktar)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionKapat)
        self.menuHakk_nda.addAction(self.actionProgram_Kaynaklar)
        self.menuHakk_nda.addSeparator()
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuHakk_nda.menuAction())
        self.toolBar.addAction(self.engine_entry)
        self.toolBar.addAction(self.gearbox_entry)
        self.toolBar.addAction(self.vehicle_entry)
        self.toolBar.addAction(self.environment_entry)
        self.toolBar.addSeparator()

        self.retranslateUi(VehicleDynamicsApp)
        
        self.actionKapat.triggered.connect(VehicleDynamicsApp.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VehicleDynamicsApp)

    def retranslateUi(self, VehicleDynamicsApp):
        _translate = QtCore.QCoreApplication.translate
        VehicleDynamicsApp.setWindowTitle(_translate("VehicleDynamicsApp", "Pancar v1.0"))
        self.vehicle_info.setTitle(_translate("VehicleDynamicsApp", "Vehicle Information"))
        self.car_model_label.setText(_translate("VehicleDynamicsApp", "Brand-Model"))
        self.engine_model_label.setText(_translate("VehicleDynamicsApp", "Engine Brand-Model"))
        self.user_info.setTitle(_translate("VehicleDynamicsApp", "User Information"))
        self.user_info_label_area.setText(_translate("VehicleDynamicsApp", "   Name Surname"))
        __sortingEnabled = self.engine_torque_speed_list.isSortingEnabled()
        self.engine_torque_speed_list.setSortingEnabled(False)
        item = self.engine_torque_speed_list.item(0)
        item.setText(_translate("VehicleDynamicsApp", "Rb-26  "))
        item = self.engine_torque_speed_list.item(1)
        item.setText(_translate("VehicleDynamicsApp", "New Item"))
        item = self.engine_torque_speed_list.item(2)
        item.setText(_translate("VehicleDynamicsApp", "New Item"))
        item = self.engine_torque_speed_list.item(3)
        item.setText(_translate("VehicleDynamicsApp", "2jz"))
        self.engine_torque_speed_list.setSortingEnabled(__sortingEnabled)
        self.ets_list_label.setText(_translate("VehicleDynamicsApp", "Engine Torque-Speed Values"))
        self.ets_list_delete_button.setText(_translate("VehicleDynamicsApp", "-"))
        __sortingEnabled = self.gearbox_list.isSortingEnabled()
        self.gearbox_list.setSortingEnabled(False)
        item = self.gearbox_list.item(0)
        item.setText(_translate("VehicleDynamicsApp", "Toyota supra 5"))
        item = self.gearbox_list.item(1)
        item.setText(_translate("VehicleDynamicsApp", "Nissan GTR 6"))
        self.gearbox_list.setSortingEnabled(__sortingEnabled)
        self.gearbox_list_label.setText(_translate("VehicleDynamicsApp", "Gearbox Parameters"))
        self.gearbox_list_delete_button.setText(_translate("VehicleDynamicsApp", "-"))
        __sortingEnabled = self.vehicle_list.isSortingEnabled()
        self.vehicle_list.setSortingEnabled(False)
        item = self.vehicle_list.item(0)
        item.setText(_translate("VehicleDynamicsApp", "Toyota Supra "))
        item = self.vehicle_list.item(1)
        item.setText(_translate("VehicleDynamicsApp", "Nissan GTR R34"))
        self.vehicle_list.setSortingEnabled(__sortingEnabled)
        self.vehicle_list_label.setText(_translate("VehicleDynamicsApp", "Vehicle Parameters"))
        self.vehicle_list_delete_button.setText(_translate("VehicleDynamicsApp", "-"))
        __sortingEnabled = self.environment_list.isSortingEnabled()
        self.environment_list.setSortingEnabled(False)
        item = self.environment_list.item(0)
        item.setText(_translate("VehicleDynamicsApp", "Analysis 1"))
        item = self.environment_list.item(1)
        item.setText(_translate("VehicleDynamicsApp", "high"))
        self.environment_list.setSortingEnabled(__sortingEnabled)
        self.env_list_label.setText(_translate("VehicleDynamicsApp", "Environmental Paramaters"))
        self.env_list_delete_button.setText(_translate("VehicleDynamicsApp", "-"))
        self.graph_area.setTitle(_translate("VehicleDynamicsApp", "Performance Graphs"))
        self.enginev_vehiclev.setText(_translate("VehicleDynamicsApp", "Engine Speed vs Vehicle Speed"))
        self.torque_enginev.setText(_translate("VehicleDynamicsApp", "Torque vs Speed"))
        self.torque_enginev_power.setText(_translate("VehicleDynamicsApp", "Torque vs Speed vs Power"))
        self.tractiveF_vehiclev.setText(_translate("VehicleDynamicsApp", "Tractive Effort (without res.) vs Vehicle Speed"))
        self.tractiveFnet_vehiclev.setText(_translate("VehicleDynamicsApp", "Tractive Effort vs Vehicle Speed"))
        self.menuDosya.setTitle(_translate("VehicleDynamicsApp", "File"))
        self.menuHakk_nda.setTitle(_translate("VehicleDynamicsApp", "About"))
        self.toolBar.setWindowTitle(_translate("VehicleDynamicsApp", "toolBar"))
        self.actionKapat.setText(_translate("VehicleDynamicsApp", "close"))
        self.actionProgram_Kaynaklar.setText(_translate("VehicleDynamicsApp", "eray.studio"))
        self.vehicle_entry.setText(_translate("VehicleDynamicsApp", "Vehicle"))
        self.vehicle_entry.setToolTip(_translate("VehicleDynamicsApp", "vehicle"))
        self.gearbox_entry.setText(_translate("VehicleDynamicsApp", "gearbox"))
        self.gearbox_entry.setToolTip(_translate("VehicleDynamicsApp", "gearbox"))
        self.environment_entry.setText(_translate("VehicleDynamicsApp", "environment"))
        self.environment_entry.setToolTip(_translate("VehicleDynamicsApp", "env"))
        self.engine_entry.setText(_translate("VehicleDynamicsApp", "engine"))
        self.actionDosyaya_Aktar.setText(_translate("VehicleDynamicsApp", "export to .pdf"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VehicleDynamicsApp = QtWidgets.QMainWindow()
    ui = Ui_VehicleDynamicsApp()
    ui.setupUi(VehicleDynamicsApp)
    VehicleDynamicsApp.show()
    sys.exit(app.exec())
