# Form implementation generated from reading ui file 'vehicle.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from . import widgets_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 253)
        Dialog.setMinimumSize(QtCore.QSize(350, 253))
        Dialog.setMaximumSize(QtCore.QSize(350, 253))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/vehicle.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(25,25,25);\n"
"background-color: rgb(255, 255, 255);")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(parent=Dialog)
        self.label_16.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(161, 0))
        self.label_11.setStyleSheet("\n"
"")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_14 = QtWidgets.QLabel(parent=Dialog)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(parent=Dialog)
        self.label_15.setMinimumSize(QtCore.QSize(120, 0))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(parent=Dialog)
        self.label_17.setMinimumSize(QtCore.QSize(120, 0))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(parent=Dialog)
        self.label_18.setMinimumSize(QtCore.QSize(120, 0))
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.arac_ismi = QtWidgets.QLineEdit(parent=Dialog)
        self.arac_ismi.setObjectName("arac_ismi")
        self.verticalLayout.addWidget(self.arac_ismi)
        self.arac_kutlesi = QtWidgets.QLineEdit(parent=Dialog)
        self.arac_kutlesi.setObjectName("arac_kutlesi")
        self.verticalLayout.addWidget(self.arac_kutlesi)
        self.cf_aero = QtWidgets.QLineEdit(parent=Dialog)
        self.cf_aero.setObjectName("cf_aero")
        self.verticalLayout.addWidget(self.cf_aero)
        self.izdusum_alan = QtWidgets.QLineEdit(parent=Dialog)
        self.izdusum_alan.setObjectName("izdusum_alan")
        self.verticalLayout.addWidget(self.izdusum_alan)
        self.yuvarlanma_direnc = QtWidgets.QLineEdit(parent=Dialog)
        self.yuvarlanma_direnc.setObjectName("yuvarlanma_direnc")
        self.verticalLayout.addWidget(self.yuvarlanma_direnc)
        self.teker_efektif_r = QtWidgets.QLineEdit(parent=Dialog)
        self.teker_efektif_r.setObjectName("teker_efektif_r")
        self.verticalLayout.addWidget(self.teker_efektif_r)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.arac_kaydet = QtWidgets.QPushButton(parent=self.frame)
        self.arac_kaydet.setMinimumSize(QtCore.QSize(141, 21))
        self.arac_kaydet.setMaximumSize(QtCore.QSize(141, 21))
        self.arac_kaydet.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.arac_kaydet.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.arac_kaydet.setStyleSheet("QPushButton{\n"
"border-radius:5px;\n"
"font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);\n"
"background-color: rgb(25,25,25);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color:rgb(239, 239, 239);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"}")
        self.arac_kaydet.setObjectName("arac_kaydet")
        self.horizontalLayout_4.addWidget(self.arac_kaydet)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Araç"))
        self.label_16.setText(_translate("Dialog", "Araç Parametreleri"))
        self.label_10.setText(_translate("Dialog", "Araç ismi"))
        self.label_11.setText(_translate("Dialog", "Araç kütlesi (kg)"))
        self.label_14.setText(_translate("Dialog", "Cf aerodinamik direnç katsayısı"))
        self.label_15.setText(_translate("Dialog", "Af araç izdüşüm alanı (m^2)"))
        self.label_17.setText(_translate("Dialog", "Yuvarlanma direnç katsayısı"))
        self.label_18.setText(_translate("Dialog", "Tekerlek efektif yarıçapı (m)"))
        self.arac_kaydet.setText(_translate("Dialog", "KAYDET"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec())
