# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VehicleDynamicsApp(object):
    def setupUi(self, VehicleDynamicsApp):
        VehicleDynamicsApp.setObjectName("VehicleDynamicsApp")
        VehicleDynamicsApp.setEnabled(True)
        VehicleDynamicsApp.resize(923, 623)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VehicleDynamicsApp.sizePolicy().hasHeightForWidth())
        VehicleDynamicsApp.setSizePolicy(sizePolicy)
        VehicleDynamicsApp.setMinimumSize(QtCore.QSize(923, 623))
        VehicleDynamicsApp.setMaximumSize(QtCore.QSize(923, 623))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(9)
        font.setItalic(False)
        font.setKerning(True)
        VehicleDynamicsApp.setFont(font)
        VehicleDynamicsApp.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        VehicleDynamicsApp.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/assets/dark-car-from-side-vector-9761198.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        VehicleDynamicsApp.setWindowIcon(icon)
        VehicleDynamicsApp.setToolTipDuration(-1)
        VehicleDynamicsApp.setStyleSheet("font: 350 9pt \"Bahnschrift SemiLight\";\n"
"background-color: rgb(28,28,28);\n"
"color:rgb(255,255,255);")
        VehicleDynamicsApp.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=VehicleDynamicsApp)
        self.centralwidget.setMinimumSize(QtCore.QSize(923, 546))
        self.centralwidget.setMaximumSize(QtCore.QSize(923, 609))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 609))
        self.frame_2.setStyleSheet("background-color: rgb(5,5,5);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_19.setContentsMargins(6, -1, 0, 8)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.car = QtWidgets.QFrame(parent=self.frame_2)
        self.car.setStyleSheet("font: 900 8pt \"Segoe UI\";\n"
"background-color: rgb(15,15,15);")
        self.car.setObjectName("car")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.car)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setContentsMargins(4, -1, -1, -1)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_28 = QtWidgets.QLabel(parent=self.car)
        self.label_28.setMinimumSize(QtCore.QSize(411, 301))
        self.label_28.setMaximumSize(QtCore.QSize(411, 301))
        self.label_28.setAutoFillBackground(False)
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/img/icons/dark-car-from-side-vector-9761198.jpg"))
        self.label_28.setScaledContents(True)
        self.label_28.setWordWrap(False)
        self.label_28.setOpenExternalLinks(False)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_34.addWidget(self.label_28)
        self.widget_10 = QtWidgets.QWidget(parent=self.car)
        self.widget_10.setMinimumSize(QtCore.QSize(371, 161))
        self.widget_10.setMaximumSize(QtCore.QSize(123213, 213123))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_29.setMinimumSize(QtCore.QSize(0, 1))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 1))
        self.label_29.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_35.addWidget(self.label_29)
        self.groupBox_10 = QtWidgets.QGroupBox(parent=self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 700 8pt \"Segoe UI\";")
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_11 = QtWidgets.QWidget(parent=self.groupBox_10)
        self.widget_11.setStyleSheet("font: 12px \"Small Fonts\";")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_30 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_37.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_37.addWidget(self.label_31)
        self.horizontalLayout_17.addWidget(self.widget_11)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.user_info_13 = QtWidgets.QLineEdit(parent=self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_info_13.sizePolicy().hasHeightForWidth())
        self.user_info_13.setSizePolicy(sizePolicy)
        self.user_info_13.setMinimumSize(QtCore.QSize(200, 20))
        self.user_info_13.setMaximumSize(QtCore.QSize(200, 20))
        self.user_info_13.setStyleSheet("color:rgb(0,0,0);\n"
"background-color: rgb(168, 168, 168);")
        self.user_info_13.setObjectName("user_info_13")
        self.verticalLayout_38.addWidget(self.user_info_13)
        self.user_info_14 = QtWidgets.QLineEdit(parent=self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_info_14.sizePolicy().hasHeightForWidth())
        self.user_info_14.setSizePolicy(sizePolicy)
        self.user_info_14.setMinimumSize(QtCore.QSize(200, 20))
        self.user_info_14.setMaximumSize(QtCore.QSize(200, 20))
        self.user_info_14.setStyleSheet("color:rgb(0,0,0);\n"
"background-color: rgb(168, 168, 168);")
        self.user_info_14.setObjectName("user_info_14")
        self.verticalLayout_38.addWidget(self.user_info_14)
        self.horizontalLayout_17.addLayout(self.verticalLayout_38)
        self.verticalLayout_36.addLayout(self.horizontalLayout_17)
        self.verticalLayout_35.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(parent=self.widget_10)
        self.groupBox_11.setStyleSheet("color:rgb(255,255,255);\n"
"font: 700 8pt \"Segoe UI\";")
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_32 = QtWidgets.QLabel(parent=self.groupBox_11)
        self.label_32.setStyleSheet("font: 9pt \"Small Fonts\";")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_18.addWidget(self.label_32)
        self.user_info_15 = QtWidgets.QLineEdit(parent=self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_info_15.sizePolicy().hasHeightForWidth())
        self.user_info_15.setSizePolicy(sizePolicy)
        self.user_info_15.setMinimumSize(QtCore.QSize(200, 20))
        self.user_info_15.setMaximumSize(QtCore.QSize(200, 20))
        self.user_info_15.setStyleSheet("color:rgb(0,0,0);\n"
"background-color: rgb(168, 168, 168);")
        self.user_info_15.setObjectName("user_info_15")
        self.horizontalLayout_18.addWidget(self.user_info_15)
        self.verticalLayout_39.addLayout(self.horizontalLayout_18)
        self.verticalLayout_35.addWidget(self.groupBox_11)
        self.verticalLayout_34.addWidget(self.widget_10)
        self.horizontalLayout.addLayout(self.verticalLayout_34)
        self.horizontalLayout_20.addWidget(self.car)
        self.frame = QtWidgets.QFrame(parent=self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(473, 0))
        self.frame.setMaximumSize(QtCore.QSize(473, 16777215))
        self.frame.setStyleSheet("")
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame1 = QtWidgets.QFrame(parent=self.frame)
        self.frame1.setMinimumSize(QtCore.QSize(456, 1))
        self.frame1.setMaximumSize(QtCore.QSize(456, 123123))
        self.frame1.setStyleSheet("background-color: rgb(15,15,15);\n"
"border-radius:3px;")
        self.frame1.setObjectName("frame1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.torque_rpm_list = QtWidgets.QListWidget(parent=self.frame1)
        self.torque_rpm_list.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"font: 10pt \"Segoe UI\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(102, 0, 0);\n"
"")
        self.torque_rpm_list.setObjectName("torque_rpm_list")
        item = QtWidgets.QListWidgetItem()
        self.torque_rpm_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.torque_rpm_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.torque_rpm_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.torque_rpm_list.addItem(item)
        self.verticalLayout_3.addWidget(self.torque_rpm_list)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.frame1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButton_3.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButton_3.setSizeIncrement(QtCore.QSize(0, 10))
        self.pushButton_3.setBaseSize(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"padding-bottom:4px;\n"
"padding-left:1px;\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.label_3 = QtWidgets.QLabel(parent=self.frame1)
        self.label_3.setMinimumSize(QtCore.QSize(1, 100))
        self.label_3.setMaximumSize(QtCore.QSize(1, 100))
        self.label_3.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gearbox_list = QtWidgets.QListWidget(parent=self.frame1)
        self.gearbox_list.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"font: 10pt \"Segoe UI\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(102, 0, 0);\n"
"")
        self.gearbox_list.setObjectName("gearbox_list")
        item = QtWidgets.QListWidgetItem()
        self.gearbox_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gearbox_list.addItem(item)
        self.verticalLayout_4.addWidget(self.gearbox_list)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(parent=self.frame1)
        self.label_7.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButton_4.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"padding-bottom:4px;\n"
"padding-left:1px;\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.label_2 = QtWidgets.QLabel(parent=self.frame1)
        self.label_2.setMinimumSize(QtCore.QSize(0, 1))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.label_2.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.car_param = QtWidgets.QListWidget(parent=self.frame1)
        self.car_param.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"font: 10pt \"Segoe UI\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(102, 0, 0);\n"
"")
        self.car_param.setObjectName("car_param")
        item = QtWidgets.QListWidgetItem()
        self.car_param.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.car_param.addItem(item)
        self.verticalLayout_6.addWidget(self.car_param)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(parent=self.frame1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButton_5.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"padding-bottom:4px;\n"
"padding-left:1px;\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.label_4 = QtWidgets.QLabel(parent=self.frame1)
        self.label_4.setMinimumSize(QtCore.QSize(1, 100))
        self.label_4.setMaximumSize(QtCore.QSize(1, 100))
        self.label_4.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.env_param = QtWidgets.QListWidget(parent=self.frame1)
        self.env_param.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"font: 10pt \"Segoe UI\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(102, 0, 0);\n"
"")
        self.env_param.setObjectName("env_param")
        item = QtWidgets.QListWidgetItem()
        self.env_param.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.env_param.addItem(item)
        self.verticalLayout_7.addWidget(self.env_param)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(parent=self.frame1)
        self.label_9.setStyleSheet("font: 700 11px \"Segoe UI\";\n"
"color:rgb(210,210,210);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButton_6.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"padding-bottom:4px;\n"
"padding-left:1px;\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.addWidget(self.frame1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(456, 150))
        self.groupBox.setMaximumSize(QtCore.QSize(456, 150))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("selection-color: rgb(17, 17, 17);\n"
"font: 700 italic 9pt \"Segoe UI\";\n"
"color: rgb(134,1,22);")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rpm_v = QtWidgets.QPushButton(parent=self.groupBox)
        self.rpm_v.setMinimumSize(QtCore.QSize(180, 28))
        self.rpm_v.setMaximumSize(QtCore.QSize(180, 20))
        self.rpm_v.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rpm_v.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"color:rgb(230,230,230);\n"
"font: 9pt \"Gill Sans MT\";\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.rpm_v.setIconSize(QtCore.QSize(16, 20))
        self.rpm_v.setObjectName("rpm_v")
        self.verticalLayout.addWidget(self.rpm_v)
        self.torque_rpm = QtWidgets.QPushButton(parent=self.groupBox)
        self.torque_rpm.setMinimumSize(QtCore.QSize(180, 28))
        self.torque_rpm.setMaximumSize(QtCore.QSize(180, 20))
        self.torque_rpm.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.torque_rpm.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"color:rgb(230,230,230);\n"
"font: 9pt \"Gill Sans MT\";\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.torque_rpm.setObjectName("torque_rpm")
        self.verticalLayout.addWidget(self.torque_rpm)
        self.torque_rpm_power = QtWidgets.QPushButton(parent=self.groupBox)
        self.torque_rpm_power.setEnabled(True)
        self.torque_rpm_power.setMinimumSize(QtCore.QSize(180, 28))
        self.torque_rpm_power.setMaximumSize(QtCore.QSize(180, 20))
        self.torque_rpm_power.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.torque_rpm_power.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"color:rgb(230,230,230);\n"
"font: 9pt \"Gill Sans MT\";\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.torque_rpm_power.setObjectName("torque_rpm_power")
        self.verticalLayout.addWidget(self.torque_rpm_power)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.F_v = QtWidgets.QPushButton(parent=self.groupBox)
        self.F_v.setMinimumSize(QtCore.QSize(230, 40))
        self.F_v.setMaximumSize(QtCore.QSize(210, 28))
        self.F_v.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.F_v.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"color:rgb(230,230,230);\n"
"font: 9pt \"Gill Sans MT\";\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.F_v.setObjectName("F_v")
        self.verticalLayout_2.addWidget(self.F_v)
        self.Fnet_v = QtWidgets.QPushButton(parent=self.groupBox)
        self.Fnet_v.setMinimumSize(QtCore.QSize(230, 40))
        self.Fnet_v.setMaximumSize(QtCore.QSize(205, 28))
        self.Fnet_v.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Fnet_v.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"color:rgb(230,230,230);\n"
"font: 9pt \"Gill Sans MT\";\n"
"background-color: rgb(20,20,20);\n"
"cursor:pointer;\n"
"border: 1px solid rgb(168, 168, 168);\n"
"}\n"
"QPushButton:hover {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed {\n"
"color:rgb(9, 9, 9);\n"
"background-color: rgb(150,150,150);\n"
"border: 1px solid rgb(150,150,150);\n"
"}")
        self.Fnet_v.setObjectName("Fnet_v")
        self.verticalLayout_2.addWidget(self.Fnet_v)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.horizontalLayout_20.addWidget(self.frame)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.verticalLayout_5.addWidget(self.frame_2)
        VehicleDynamicsApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VehicleDynamicsApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 34))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(parent=self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menuHakk_nda = QtWidgets.QMenu(parent=self.menubar)
        self.menuHakk_nda.setObjectName("menuHakk_nda")
        VehicleDynamicsApp.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(parent=VehicleDynamicsApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(9)
        font.setItalic(False)
        font.setKerning(True)
        self.toolBar.setFont(font)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolBar.setAcceptDrops(True)
        self.toolBar.setToolTip("")
        self.toolBar.setStatusTip("")
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setObjectName("toolBar")
        VehicleDynamicsApp.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionKapat = QtGui.QAction(parent=VehicleDynamicsApp)
        font = QtGui.QFont()
        self.actionKapat.setFont(font)
        self.actionKapat.setObjectName("actionKapat")
        self.actionProgram_Kaynaklar = QtGui.QAction(parent=VehicleDynamicsApp)
        font = QtGui.QFont()
        self.actionProgram_Kaynaklar.setFont(font)
        self.actionProgram_Kaynaklar.setObjectName("actionProgram_Kaynaklar")
        self.vehicle_entry = QtGui.QAction(parent=VehicleDynamicsApp)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icons/vehicle.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vehicle_entry.setIcon(icon1)
        self.vehicle_entry.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.vehicle_entry.setObjectName("vehicle_entry")
        self.gearbox_entry = QtGui.QAction(parent=VehicleDynamicsApp)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icons/gearbox2.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.gearbox_entry.setIcon(icon2)
        self.gearbox_entry.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.gearbox_entry.setObjectName("gearbox_entry")
        self.environment_entry = QtGui.QAction(parent=VehicleDynamicsApp)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icons/road.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.environment_entry.setIcon(icon3)
        self.environment_entry.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.environment_entry.setObjectName("environment_entry")
        self.engine_entry = QtGui.QAction(parent=VehicleDynamicsApp)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/icons/engine.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.engine_entry.setIcon(icon4)
        self.engine_entry.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.engine_entry.setObjectName("engine_entry")
        self.actionDosyaya_Aktar = QtGui.QAction(parent=VehicleDynamicsApp)
        self.actionDosyaya_Aktar.setObjectName("actionDosyaya_Aktar")
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionDosyaya_Aktar)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionKapat)
        self.menuHakk_nda.addAction(self.actionProgram_Kaynaklar)
        self.menuHakk_nda.addSeparator()
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuHakk_nda.menuAction())
        self.toolBar.addAction(self.engine_entry)
        self.toolBar.addAction(self.gearbox_entry)
        self.toolBar.addAction(self.vehicle_entry)
        self.toolBar.addAction(self.environment_entry)
        self.toolBar.addSeparator()

        self.retranslateUi(VehicleDynamicsApp)
        self.actionKapat.triggered.connect(VehicleDynamicsApp.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VehicleDynamicsApp)
        VehicleDynamicsApp.setTabOrder(self.car_param, self.env_param)
        VehicleDynamicsApp.setTabOrder(self.env_param, self.torque_rpm)
        VehicleDynamicsApp.setTabOrder(self.torque_rpm, self.torque_rpm_power)
        VehicleDynamicsApp.setTabOrder(self.torque_rpm_power, self.rpm_v)
        VehicleDynamicsApp.setTabOrder(self.rpm_v, self.F_v)
        VehicleDynamicsApp.setTabOrder(self.F_v, self.Fnet_v)

    def retranslateUi(self, VehicleDynamicsApp):
        _translate = QtCore.QCoreApplication.translate
        VehicleDynamicsApp.setWindowTitle(_translate("VehicleDynamicsApp", "Pancar V1.0"))
        self.groupBox_10.setTitle(_translate("VehicleDynamicsApp", "Vehicle Information"))
        self.label_30.setText(_translate("VehicleDynamicsApp", "Brand-Model"))
        self.label_31.setText(_translate("VehicleDynamicsApp", "Engine Brand-Model"))
        self.groupBox_11.setTitle(_translate("VehicleDynamicsApp", "User Information"))
        self.label_32.setText(_translate("VehicleDynamicsApp", "   Name Surname"))
        __sortingEnabled = self.torque_rpm_list.isSortingEnabled()
        self.torque_rpm_list.setSortingEnabled(False)
        item = self.torque_rpm_list.item(0)
        item.setText(_translate("VehicleDynamicsApp", "Rb-26  "))
        item = self.torque_rpm_list.item(1)
        item.setText(_translate("VehicleDynamicsApp", "New Item"))
        item = self.torque_rpm_list.item(2)
        item.setText(_translate("VehicleDynamicsApp", "New Item"))
        item = self.torque_rpm_list.item(3)
        item.setText(_translate("VehicleDynamicsApp", "2jz"))
        self.torque_rpm_list.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("VehicleDynamicsApp", "Engine Torque-Speed Values"))
        self.pushButton_3.setText(_translate("VehicleDynamicsApp", "-"))
        __sortingEnabled = self.gearbox_list.isSortingEnabled()
        self.gearbox_list.setSortingEnabled(False)
        item = self.gearbox_list.item(0)
        item.setText(_translate("VehicleDynamicsApp", "Toyota supra 5"))
        item = self.gearbox_list.item(1)
        item.setText(_translate("VehicleDynamicsApp", "Nissan GTR 6"))
        self.gearbox_list.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("VehicleDynamicsApp", "Gearbox Parameters"))
        self.pushButton_4.setText(_translate("VehicleDynamicsApp", "-"))
        __sortingEnabled = self.car_param.isSortingEnabled()
        self.car_param.setSortingEnabled(False)
        item = self.car_param.item(0)
        item.setText(_translate("VehicleDynamicsApp", "Toyota Supra "))
        item = self.car_param.item(1)
        item.setText(_translate("VehicleDynamicsApp", "Nissan GTR R34"))
        self.car_param.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("VehicleDynamicsApp", "Vehicle Parameters"))
        self.pushButton_5.setText(_translate("VehicleDynamicsApp", "-"))
        __sortingEnabled = self.env_param.isSortingEnabled()
        self.env_param.setSortingEnabled(False)
        item = self.env_param.item(0)
        item.setText(_translate("VehicleDynamicsApp", "Analysis 1"))
        item = self.env_param.item(1)
        item.setText(_translate("VehicleDynamicsApp", "high"))
        self.env_param.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("VehicleDynamicsApp", "Environmental Paramaters"))
        self.pushButton_6.setText(_translate("VehicleDynamicsApp", "-"))
        self.groupBox.setTitle(_translate("VehicleDynamicsApp", "Performance Graphs"))
        self.rpm_v.setText(_translate("VehicleDynamicsApp", "Engine Speed vs Vehicle Speed"))
        self.torque_rpm.setText(_translate("VehicleDynamicsApp", "Torque vs Speed"))
        self.torque_rpm_power.setText(_translate("VehicleDynamicsApp", "Torque vs Speed vs Power"))
        self.F_v.setText(_translate("VehicleDynamicsApp", "Tractive Effort (without res.) vs Vehicle Speed"))
        self.Fnet_v.setText(_translate("VehicleDynamicsApp", "Tractive Effort vs Vehicle Speed"))
        self.menuDosya.setTitle(_translate("VehicleDynamicsApp", "File"))
        self.menuHakk_nda.setTitle(_translate("VehicleDynamicsApp", "About"))
        self.toolBar.setWindowTitle(_translate("VehicleDynamicsApp", "toolBar"))
        self.actionKapat.setText(_translate("VehicleDynamicsApp", "close"))
        self.actionProgram_Kaynaklar.setText(_translate("VehicleDynamicsApp", "eray.studio"))
        self.vehicle_entry.setText(_translate("VehicleDynamicsApp", "Vehicle"))
        self.vehicle_entry.setToolTip(_translate("VehicleDynamicsApp", "vehicle"))
        self.gearbox_entry.setText(_translate("VehicleDynamicsApp", "gearbox"))
        self.gearbox_entry.setToolTip(_translate("VehicleDynamicsApp", "gearbox"))
        self.environment_entry.setText(_translate("VehicleDynamicsApp", "environment"))
        self.environment_entry.setToolTip(_translate("VehicleDynamicsApp", "env"))
        self.engine_entry.setText(_translate("VehicleDynamicsApp", "engine"))
        self.actionDosyaya_Aktar.setText(_translate("VehicleDynamicsApp", "export to .pdf"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VehicleDynamicsApp = QtWidgets.QMainWindow()
    ui = Ui_VehicleDynamicsApp()
    ui.setupUi(VehicleDynamicsApp)
    VehicleDynamicsApp.show()
    sys.exit(app.exec())
